sudo: required

language: bash

dist: trusty

env:
  - VERSION=latest

services:
  - docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="willfarrell/letsencrypt:$VERSION"

script:
  - docker build --pull -t "$image" .
  - docker run -d "$image"
  - docker ps | grep "$image" | awk '{print $1}' || { exit 1; }
